apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: dcfs-worker2
  name: dcfs-worker2
spec:
  clusterIP: None
  ports:
    - name: "8043"
      protocol: TCP
      port: 8043
      targetPort: 8043
  selector:
    io.kompose.service: dcfs-worker2
status:
  loadBalancer: {}
