apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: flask
  name: flask
spec:
  type: NodePort
  ports:
    - name: "5000"
      protocol: TCP
      port: 5500
      targetPort: 5500
  selector:
    io.kompose.service: flask
status:
  loadBalancer: {}
