# For kubernetes v1.10
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-namenode-logs
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /hadoop/dfs/namelogs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker01
