apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: zoo2
  name: zoo2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zoo2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.network/hdsdcfsdocker-hdrs-network: "true"
        io.kompose.service: zoo2
    spec:
      containers:
        - env:
            - name: ZOO_ADMINSERVER_ENABLED
              value: "false"
            - name: ZOO_AUTOPURGE_PURGEINTERVAL
              value: "0"
            - name: ZOO_AUTOPURGE_SNAPRETAINCOUNT
              value: "3"
            - name: ZOO_CONF_DIR
              value: /zookeeper/conf
            - name: ZOO_DATA_DIR
              value: /zookeeper/data
            - name: ZOO_DATA_LOG_DIR
              value: /zookeeper/datalog
            - name: ZOO_INIT_LIMIT
              value: "5"
            - name: ZOO_LOG_DIR
              value: /zookeeper/logs
            - name: ZOO_MAX_CLIENT_CNXNS
              value: "60"
            - name: ZOO_MY_ID
              value: "2"
            - name: ZOO_SERVERS
              value: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181
            - name: ZOO_STANDALONE_ENABLED
              value: "true"
            - name: ZOO_SYNC_LIMIT
              value: "2"
            - name: ZOO_TICK_TIME
              value: "2000"
          image: cwbw/zookeeper
          name: zoo2
          ports:
            - containerPort: 2181
            - containerPort: 3888
            - containerPort: 2888
          resources: {}
          volumeMounts:
            - mountPath: /zookeeper/data
              name: zoo2-data
      hostname: zoo2
      restartPolicy: Always
      volumes:
        - name: zoo2-data
          emptyDir: {}
status: {}
