apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: datanode1
  name: datanode1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: datanode1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.network/hdsdcfsdocker-hdrs-network: "true"
        io.kompose.service: datanode1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker01
      containers:
        - env:
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://namenode:9000
            - name: CORE_CONF_hadoop_http_staticuser_user
              value: root
            - name: CORE_CONF_hadoop_proxyuser_hue_groups
              value: '*'
            - name: CORE_CONF_hadoop_proxyuser_hue_hosts
              value: '*'
            - name: CORE_CONF_io_compression_codecs
              value: org.apache.hadoop.io.compress.SnappyCodec
            - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
              value: "false"
            - name: HDFS_CONF_dfs_permissions_enabled
              value: "false"
            - name: HDFS_CONF_dfs_webhdfs_enabled
              value: "true"
            - name: MAPRED_CONF_mapred_child_java_opts
              value: -Xmx4096m
            - name: MAPRED_CONF_mapreduce_framework_name
              value: yarn
            - name: MAPRED_CONF_mapreduce_map_env
              value: HADOOP_MAPRED_HOME=/opt/hadoop-3.2.2/
            - name: MAPRED_CONF_mapreduce_map_java_opts
              value: -Xmx3072m
            - name: MAPRED_CONF_mapreduce_map_memory_mb
              value: "4096"
            - name: MAPRED_CONF_mapreduce_reduce_env
              value: HADOOP_MAPRED_HOME=/opt/hadoop-3.2.2/
            - name: MAPRED_CONF_mapreduce_reduce_java_opts
              value: -Xmx6144m
            - name: MAPRED_CONF_mapreduce_reduce_memory_mb
              value: "8192"
            - name: MAPRED_CONF_yarn_app_mapreduce_am_env
              value: HADOOP_MAPRED_HOME=/opt/hadoop-3.2.2/
            - name: YARN_CONF_mapred_map_output_compress_codec
              value: org.apache.hadoop.io.compress.SnappyCodec
            - name: YARN_CONF_mapreduce_map_output_compress
              value: "true"
            - name: YARN_CONF_yarn_log___aggregation___enable
              value: "false"
            - name: YARN_CONF_yarn_log_server_url
              value: http://historyserver:8188/applicationhistory/logs/
            - name: YARN_CONF_yarn_nodemanager_aux___services
              value: mapreduce_shuffle
            - name: YARN_CONF_yarn_nodemanager_disk___health___checker_max___disk___utilization___per___disk___percentage
              value: "98.5"
            - name: YARN_CONF_yarn_nodemanager_remote___app___log___dir
              value: /app-logs
            - name: YARN_CONF_yarn_nodemanager_resource_cpu___vcores
              value: "8"
            - name: YARN_CONF_yarn_nodemanager_resource_memory___mb
              value: "16384"
            - name: YARN_CONF_yarn_nodemanager_webapp_address
              value: ${yarn.nodemanager.hostname}:8042
            - name: YARN_CONF_yarn_resourcemanager_address
              value: resourcemanager:8032
            - name: YARN_CONF_yarn_resourcemanager_fs_state___store_uri
              value: /rmstate
            - name: YARN_CONF_yarn_resourcemanager_hostname
              value: resourcemanager
            - name: YARN_CONF_yarn_resourcemanager_recovery_enabled
              value: "false"
            - name: YARN_CONF_yarn_resourcemanager_resource__tracker_address
              value: resourcemanager:8031
            - name: YARN_CONF_yarn_resourcemanager_scheduler_address
              value: resourcemanager:8030
            - name: YARN_CONF_yarn_resourcemanager_scheduler_class
              value: org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler
            - name: YARN_CONF_yarn_resourcemanager_store_class
              value: org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
            - name: YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled
              value: "false"
            - name: YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___mb
              value: "8192"
            - name: YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___vcores
              value: "4"
            - name: YARN_CONF_yarn_timeline___service_enabled
              value: "false"
            - name: YARN_CONF_yarn_timeline___service_generic___application___history_enabled
              value: "false"
            - name: YARN_CONF_yarn_timeline___service_hostname
              value: historyserver
          image: cwbw/hadoop-datanode
          name: datanode1
          ports: 
            - containerPort: 9820
          resources: {}
          volumeMounts:
            - mountPath: /hadoop/dfs/data
              name: hadoop-datanode1
      hostname: datanode1
      restartPolicy: Always
      volumes:
        - name: hadoop-datanode1
          persistentVolumeClaim:
            claimName: hadoop-datanode1 
