apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: dcfs-worker1
  name: dcfs-worker1
spec:
  clusterIP: None
  ports:
    - name: "8042"
      protocol: TCP
      port: 8042
      targetPort: 8042
  selector:
    io.kompose.service: dcfs-worker1
status:
  loadBalancer: {}
