apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: namenode
  name: namenode
spec:
  externalIPs:
    - 192.168.103.209
  ports:
    - name: "9870"
      protocol: TCP
      port: 9870
      targetPort: 9870
    - name: "9000"
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: namenode
status:
  loadBalancer: {}
